name: Daily Debrief 

on:
  schedule:
    # Every 2 minutes from 10:00–10:59 IST (04:30–05:29 UTC)
    - cron: "30-59/2 4 * * *"
    # Every 2 minutes from 11:00–11:00 IST (05:00–05:30 UTC)
    - cron: "0-30/2 5 * * *"

  workflow_dispatch:

jobs:
  send-debrief:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          
      - name: Install dependencies
        run: npm install

      - name: Run Daily Debrief
        run: node index.js
