name: Daily Debrief

on:
  schedule:
    # Every 2 minutes between 10:45–11:45 AM IST (convert to UTC → 05:15–06:15 UTC)
    - cron: "*/2 5 * * *"
    - cron: "*/2 6 * * *"

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print run logs
        run: |
          echo "✅ Workflow triggered at: $(date -u)"
          echo "This run is happening every 2 minutes between 10:45–11:45 AM IST."

      - name: Send message
        run: |
          echo "🚀 Sending scheduled message at $(date -u)"
          # here you can put your curl / node / python command to send msg
