name: Daily Debrief

on:
  schedule:
    - cron: "*/2 5-6 * * *"   # Every 2 minutes between 10:40–11:40 IST (5:10–6:10 UTC)
  workflow_dispatch: # for manual runs

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print Start Log
        run: echo "::notice:: Workflow triggered at $(date -u)"

      - name: Run Script
        run: |
          echo "::notice:: Starting Daily Debrief script..."
          # your actual script or API call
          echo "::notice:: Message sent successfully at $(date -u)"

      - name: Print End Log
        run: echo "::notice:: Workflow finished at $(date -u)"
