name: Daily Debrief 

on:
  schedule:
    # Specific times in IST
    - cron: '30 4 * * *'   # 10:00 AM IST
    - cron: '40 4 * * *'   # 10:10 AM IST
    - cron: '45 4 * * *'   # 10:15 AM IST

    # Every 5 minutes from 10:20 AM IST (04:50 UTC) to 11:00 AM IST (05:30 UTC)
    - cron: '50-59/5 4 * * *'   # 10:20, 10:25, 10:30, 10:35, 10:40, 10:45, 10:50, 10:55 AM IST
    - cron: '0-30/5 5 * * *'    # 11:00, 11:05, 11:10, 11:15, 11:20, 11:25, 11:30 AM IST

  workflow_dispatch:

jobs:
  send-debrief:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          

      - name: Install dependencies
        run: npm install

      - name: Run Daily Debrief
        run: node index.js
