name: Daily Debrief

on:
  schedule:
    # Runs every day at 16:10 IST → 10:40 UTC
    - cron: '40 10 * * *'
  workflow_dispatch:

jobs:
  send-debrief:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run Daily Debrief
        run: node index.js
